CREATE TYPE public.app_role AS ENUM ('owner_admin', 'user');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role public.app_role NOT NULL DEFAULT 'user', UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX single_owner ON public.user_roles(role) WHERE role = 'owner_admin';
CREATE FUNCTION public.is_owner() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role='owner_admin') $$;
REVOKE ALL ON FUNCTION public.is_owner() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_owner() TO authenticated, service_role;
CREATE POLICY roles_read ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_owner());
CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', plan text NOT NULL DEFAULT 'Free', unlimited_credits boolean NOT NULL DEFAULT false, credit_balance bigint DEFAULT 0 CHECK(credit_balance>=0), suspended boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), CHECK ((unlimited_credits AND credit_balance IS NULL) OR (NOT unlimited_credits AND credit_balance IS NOT NULL)));
GRANT SELECT ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid() OR public.is_owner());
CREATE TABLE public.projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, title text NOT NULL, status text NOT NULL DEFAULT 'pending', minutes numeric NOT NULL DEFAULT 0, cuts integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.projects TO authenticated;
GRANT ALL ON public.projects TO service_role;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY projects_read ON public.projects FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_owner());
CREATE TABLE public.usage_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, project_id uuid REFERENCES public.projects(id), videos integer NOT NULL DEFAULT 0, minutes numeric NOT NULL DEFAULT 0, cuts integer NOT NULL DEFAULT 0, api_calls integer NOT NULL DEFAULT 0, estimated_cost numeric NOT NULL DEFAULT 0, processing_seconds numeric NOT NULL DEFAULT 0, credits_used bigint NOT NULL DEFAULT 0, error text, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.usage_events TO authenticated;
GRANT ALL ON public.usage_events TO service_role;
ALTER TABLE public.usage_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY usage_read ON public.usage_events FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_owner());
CREATE TABLE public.credit_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id), actor_id uuid, amount bigint NOT NULL, kind text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.credit_ledger TO authenticated;
GRANT ALL ON public.credit_ledger TO service_role;
ALTER TABLE public.credit_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY ledger_read ON public.credit_ledger FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_owner());
CREATE TABLE public.payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id), amount numeric NOT NULL DEFAULT 0, credits bigint NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.payments TO authenticated;
GRANT ALL ON public.payments TO service_role;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY payments_read ON public.payments FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_owner());
CREATE FUNCTION public.create_account() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,email,display_name) VALUES(NEW.id,coalesce(NEW.email,''),coalesce(NEW.raw_user_meta_data->>'full_name','')); INSERT INTO public.user_roles(user_id,role) VALUES(NEW.id,'user'); RETURN NEW; END $$;
REVOKE ALL ON FUNCTION public.create_account() FROM PUBLIC;
CREATE TRIGGER account_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_account();
CREATE FUNCTION public.assign_initial_owner(target uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF EXISTS(SELECT 1 FROM public.user_roles WHERE role='owner_admin') THEN RAISE EXCEPTION 'Owner already assigned'; END IF; INSERT INTO public.user_roles(user_id,role) VALUES(target,'owner_admin'); UPDATE public.profiles SET unlimited_credits=true,credit_balance=NULL WHERE id=target; IF NOT FOUND THEN RAISE EXCEPTION 'Account not found'; END IF; END $$;
REVOKE ALL ON FUNCTION public.assign_initial_owner(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.assign_initial_owner(uuid) TO service_role;
CREATE FUNCTION public.admin_update_user(target uuid, credit_delta bigint DEFAULT 0, new_plan text DEFAULT NULL, new_suspended boolean DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE p public.profiles; BEGIN IF NOT public.is_owner() THEN RAISE EXCEPTION 'Você não tem permissão para acessar esta área.'; END IF; SELECT * INTO p FROM public.profiles WHERE id=target FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Usuário não encontrado'; END IF; IF EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=target AND role='owner_admin') THEN RAISE EXCEPTION 'A conta do proprietário não pode ser alterada por esta ação'; END IF; IF new_plan IS NOT NULL AND new_plan NOT IN ('Free','Starter','Pro','Business') THEN RAISE EXCEPTION 'Plano inválido'; END IF; IF p.credit_balance + credit_delta < 0 THEN RAISE EXCEPTION 'Saldo insuficiente'; END IF; UPDATE public.profiles SET credit_balance=credit_balance+credit_delta,plan=coalesce(new_plan,plan),suspended=coalesce(new_suspended,suspended) WHERE id=target; IF credit_delta<>0 THEN INSERT INTO public.credit_ledger(user_id,actor_id,amount,kind) VALUES(target,auth.uid(),credit_delta,'admin_adjustment'); END IF; END $$;
REVOKE ALL ON FUNCTION public.admin_update_user(uuid,bigint,text,boolean) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.admin_update_user(uuid,bigint,text,boolean) TO authenticated;
CREATE FUNCTION public.reserve_processing_credits(target uuid, amount bigint) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE p public.profiles; BEGIN IF amount<=0 THEN RAISE EXCEPTION 'Invalid amount'; END IF; SELECT * INTO p FROM public.profiles WHERE id=target FOR UPDATE; IF NOT FOUND OR p.suspended THEN RAISE EXCEPTION 'Account unavailable'; END IF; IF p.unlimited_credits AND EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=target AND role='owner_admin') THEN RETURN true; END IF; IF p.credit_balance IS NULL OR p.credit_balance<amount THEN RAISE EXCEPTION 'Créditos insuficientes'; END IF; UPDATE public.profiles SET credit_balance=credit_balance-amount WHERE id=target; INSERT INTO public.credit_ledger(user_id,amount,kind) VALUES(target,-amount,'processing'); RETURN true; END $$;
REVOKE ALL ON FUNCTION public.reserve_processing_credits(uuid,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_processing_credits(uuid,bigint) TO service_role;