import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Users, Wallet, Film, Coins, ShieldCheck, Search, ArrowDownToLine, RefreshCw, LockKeyhole, Activity, Clock, Cpu, Scissors } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CortesShell } from './cortes-shell';
import { getAdminData, updateAdminUser } from '@/lib/admin.functions';
import studio from '@/assets/studio.jpg';

export function AdminWorkspace({ authenticated = false }: { authenticated?: boolean }) {
  const [section, setSection] = useState('Visão geral'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [delta, setDelta] = useState('0'); const [plan, setPlan] = useState('Free'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const read = useServerFn(getAdminData); const update = useServerFn(updateAdminUser); const cache = useQueryClient();
  const query = useQuery({ queryKey: ['admin'], queryFn: () => read(), enabled: authenticated, retry: false });
  const data = query.data; const allowed = !!data;
  const users = (data?.profiles ?? []).filter(p => `${p.display_name} ${p.email}`.toLowerCase().includes(search.toLowerCase()));
  const sum = (field: 'videos' | 'minutes' | 'cuts' | 'api_calls' | 'estimated_cost' | 'credits_used' | 'processing_seconds') => data?.usage.reduce((a, u) => a + Number(u[field]), 0) ?? 0;
  const money = (n: number) => n.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
  async function mutate(target: string, suspended?: boolean) { setBusy(true); setMessage(''); try { await update({ data: suspended === undefined ? { target, credit_delta: Number(delta), new_plan: plan as 'Free' | 'Starter' | 'Pro' | 'Business' } : { target, new_suspended: suspended } }); await cache.invalidateQueries({ queryKey: ['admin'] }); setSelected(null); setMessage('Alterações salvas.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Não foi possível salvar.'); } finally { setBusy(false); } }
  function exportReport() { if (!data) return; const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'cortes-ai-relatorio.json'; a.click(); URL.revokeObjectURL(url); }
  const metrics = [{ label: 'Usuários cadastrados', value: data?.profiles.length ?? 0, icon: Users, detail: 'Contas na plataforma', color: 'mint' }, { label: 'Receita total', value: money(data?.payments.reduce((a, p) => a + Number(p.amount), 0) ?? 0), icon: Wallet, detail: 'Pagamentos confirmados', color: 'blue' }, { label: 'Vídeos processados', value: sum('videos'), icon: Film, detail: 'Processamentos concluídos', color: 'amber' }, { label: 'Créditos utilizados', value: sum('credits_used'), icon: Coins, detail: 'Consumo da plataforma', color: 'rose' }];
  return <CortesShell section={section} onSection={setSection}>
    <div className="page-heading"><div><div className="eyebrow">CENTRAL DE CONTROLE</div><h1>{section}</h1><p>Uma visão completa do seu negócio, em um só lugar.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!allowed} onClick={() => query.refetch()} title="Atualizar dados"><RefreshCw/>Atualizar</Button><Button disabled={!allowed} onClick={exportReport}><ArrowDownToLine/>Exportar relatório</Button></div></div>
    <section className="studio-banner"><img src={studio} width={1536} height={1024} alt="Estúdio de gravação com microfone profissional"/><div><span className="eyebrow">SEU NEGÓCIO. SEU CONTROLE.</span><h2>CORTES AI<span className="text-primary"> / </span>Admin</h2><p>{allowed ? '♾️ ADMINISTRADOR — CRÉDITOS ILIMITADOS' : 'O próximo capítulo da sua criação começa aqui.'}</p><span className="banner-badge"><ShieldCheck size={14}/>{allowed ? '♾️ Créditos ilimitados' : 'Ambiente de administração protegido'}</span></div></section>
    {!allowed && <div className="access-notice"><LockKeyhole size={19}/><div><strong>{query.error ? 'Você não tem permissão para acessar esta área.' : authenticated ? 'Verificando acesso…' : 'Entre com a conta do proprietário'}</strong><span>{authenticated ? 'As informações administrativas são restritas ao proprietário autorizado.' : 'Os dados do negócio ficam disponíveis somente após a autorização da sua conta.'}</span></div>{!authenticated && <Button asChild size="sm"><Link to="/auth">Acessar conta <ArrowUpRight/></Link></Button>}</div>}
    {message && <p role="status" className="my-4 text-primary">{message}</p>}
    <section className="metrics-grid">{metrics.map(({ label, value, icon: Icon, detail, color }) => <article className="metric-card" key={label}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}><Icon size={18}/></span></div><strong>{allowed ? value : '—'}</strong><small>{detail}</small></article>)}</section>
    {(section === 'Visão geral' || section === 'Uso e custos') && <div className="analytics-grid"><section className="activity-section"><div className="section-title"><div><h3>Atividade da plataforma</h3><p>Vídeos processados e cortes gerados</p></div><span className="legend"><i/> Vídeos <i/> Cortes</span></div><div className="chart-empty"><div className="chart-grid"/><div className="chart-empty-content"><Activity size={26}/><strong>{allowed ? 'Ainda sem processamentos' : 'Seus números, em tempo real'}</strong><span>{allowed ? 'A atividade aparecerá após o primeiro vídeo.' : 'A atividade será exibida após a autorização.'}</span></div></div><div className="chart-labels"><span>01</span><span>05</span><span>10</span><span>15</span><span>20</span><span>25</span><span>30</span></div></section><section className="cost-section"><div className="section-title"><div><h3>Uso e processamento</h3><p>Custos e consumo registrados</p></div><Cpu size={19}/></div><div className="cost-total"><small>Custo estimado das APIs</small><strong>{allowed ? money(sum('estimated_cost')) : '—'}</strong></div>{[{ icon: Clock, label: 'Minutos processados', value: sum('minutes') }, { icon: Cpu, label: 'Chamadas de IA', value: sum('api_calls') }, { icon: Scissors, label: 'Cortes gerados', value: sum('cuts') }].map(({ icon: Icon, label, value }) => <div className="cost-row" key={label}><span><Icon size={16}/>{label}</span><strong>{allowed ? value : '—'}</strong></div>)}<div className="cost-foot"><span className="live-label"><i/> Monitoramento ativo</span><ShieldCheck size={16}/></div></section></div>}
    {section !== 'Projetos' && section !== 'Uso e custos' && <section className="users-section"><div className="section-title"><div><h3>Usuários da plataforma <span className="count-badge">{allowed ? users.length : '—'}</span></h3><p>Gerencie contas, planos e créditos.</p></div><label className="search-input"><Search size={16}/><input aria-label="Pesquisar usuários" placeholder="Pesquisar usuários…" value={search} onChange={e => setSearch(e.target.value)} disabled={!allowed}/></label></div><div className="table-wrap"><table><thead><tr><th>USUÁRIO</th><th>PLANO</th><th>CRÉDITOS</th><th>STATUS</th><th>CADASTRO</th><th/></tr></thead><tbody>{users.map(p => <tr key={p.id}><td><strong>{p.display_name || 'Usuário'}</strong><small>{p.email}</small></td><td>{p.plan}</td><td>{p.unlimited_credits ? '♾️ Ilimitados' : p.credit_balance}</td><td><span className={p.suspended ? 'status-suspended' : 'status-active'}>{p.suspended ? 'Suspenso' : 'Ativo'}</span></td><td>{new Date(p.created_at).toLocaleDateString('pt-BR')}</td><td>{!p.unlimited_credits && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { setSelected(p.id); setPlan(p.plan); setDelta('0'); }}>Gerenciar</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => mutate(p.id, !p.suspended)}>{p.suspended ? 'Reativar' : 'Suspender'}</Button></div>}</td></tr>)}</tbody></table></div>{users.length === 0 && <div className="table-empty"><Users size={24}/><strong>{allowed ? 'Nenhum usuário encontrado' : 'Dados de usuários protegidos'}</strong><p>{allowed ? 'As novas contas aparecerão aqui.' : 'Apenas o proprietário pode visualizar e gerenciar contas.'}</p></div>}</section>}
    {section === 'Projetos' && <section className="users-section"><div className="section-title"><h3>Projetos e consumo</h3></div>{data?.projects.map(p => <div className="cost-row" key={p.id}><span>{p.title}</span><span>{p.status} · {p.minutes} min · {p.cuts} cortes</span></div>)}{!data?.projects.length && <div className="table-empty"><Film/><strong>Nenhum projeto disponível</strong></div>}</section>}
    {section === 'Uso e custos' && <section className="users-section"><div className="section-title"><h3>Resumo operacional</h3></div>{[{ label: 'Assinaturas ativas', value: data?.profiles.filter(p => p.plan !== 'Free' && !p.suspended).length ?? 0 }, { label: 'Créditos vendidos', value: data?.payments.reduce((a, p) => a + Number(p.credits), 0) ?? 0 }, { label: 'Erros registrados', value: data?.usage.filter(u => u.error).length ?? 0 }, { label: 'Tempo de processamento (s)', value: sum('processing_seconds') }].map(m => <div className="cost-row" key={m.label}><span>{m.label}</span><strong>{allowed ? m.value : '—'}</strong></div>)}</section>}
    {selected && <div className="modal-overlay"><section role="dialog" aria-modal="true" aria-label="Gerenciar usuário" className="user-modal"><h3>Gerenciar usuário</h3><label>Ajuste de créditos<input type="number" value={delta} onChange={e => setDelta(e.target.value)}/></label><label>Plano<select value={plan} onChange={e => setPlan(e.target.value)}>{['Free','Starter','Pro','Business'].map(p => <option key={p}>{p}</option>)}</select></label><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setSelected(null)}>Cancelar</Button><Button disabled={busy} onClick={() => mutate(selected)}>Salvar alterações</Button></div></section></div>}
  </CortesShell>;
}